#!/usr/bin/env python3

humanh4='--------------TCTAGAGATGGCGCCATT-TGAT-----TCCA-----GCAGCCACAAAG-CAC-----TAGAACAATCGATG---CTAAGAGGTGACAGGAAAAACAGGCTGCAAAGACCCAGACAATGGAATGCAG--CGGTGGTCAGCCTAAAACACTGTAGAAGGGCAAGATGAGCTGAGTAATTTTTAACTGGGCATCATTTTTAGAAACTGGAGTTTAAGTACCCCCTTTTCCATTTTTTCCTGAAGTCGTGGGCAGGGCGC---AAGGTCTGTGAATCGGCCGACCGGATGCAGCTGGTGTGGAGAGT---TCCCAATCAGG-------TCCGAT-TTATTACTATAT-AAAGTA-CTGCTGCGAGGCTTGCCGTGTTGCATTTTGTTTAGTACAAGACATGTCTGGGCGCGGCAAAGGCGGGAAGGGTCTGGGCAAAGGAGGCGCTAAGCGCCACCGCAAAGTTCTGCGCGACAACATTCAGGGCATCACCAAGCCCGCCATCCGACGCCTGGCACGGCGTGGAGGCGTTAAGCGCATCTCAGGCCTTATATACGAGGAGACACGCGGAGTTCTTAAAGTGTTTTTGGAGAATGTAATCCGCGATGCAGTTACCTACACGGAGCACGCCAAACGCAAGACAGTCACAGCCATGGACGTGGTTTACGCGCTCAAGCGCCAGGGCCGCACCCTGTATGGCTTTGGCGGCT-GA---GTGTTTT------ACTTACTTACACGGTTCCTCAAAGGCCCTTCTCAGGGCCACCCATGAAGTCTGTGAAAGAGCTGTAGACTAAAGAT-AGTTAATTTCTTAAGAACACTTAAACGTATGGCAGTTTTGGCAAATTAGCGATTCCACATAAGCAGT-CGCTGAAGTT-----------TGAGGTTCGGTG----------CCCCTT--TCAGCATTACTTAGTGGTTAA---AA----------------'
wheath4='AGCACCCTCCCACCTC-----ATCCCACCCTTCTGATCTCAATCCAACGTCGCATCTCCACCGTCTCGCGGATCGACCCAGCGAAGTCCCT-----------------CCCGCCCCCAAAGTCCCCCA-AAT--CTTGCAGTTC------CCTCCTAAATC------------------------------------CTCCCCA-------TATAAAC----------CAACCCCC--------------------------------CGCCCTCAGATCCCT-AAT---CCCATCGCAAGCATC--------AGACTCCCTCCAAAGCAGGCAGCAGCTCC--TCTTCTTCCTA-ATCACACTATCT-CGGAGAGG-------------------------AGCGGCCATGTCTGGGCGCGACAAGGGCGGCAAGGGGCTGGGCAAGGGCGGCGCCAAGCGGCACCGGAAGGTCCTCCGCGACAACATCCAGGGCATCACCAAGCCGGCGATCCGGAGGCTGGCCAGGAGGGGCGGCGTGAAGCGCATCTCCGGCCTCATCTACGAGGAGACCCGCGGCGTCCTCAAGATCTTCCTCGAGAACGTCATCCGCGACGCCGTCACCTACACCGAGCACGCCCGCCGCAAAACCGTCACCGCCATGGACGTCGTCTACGCGCTCAAGCGCCAGGGCCGCACCCTCTACGGCTTCGGAGGCTAGATTTGTGTGGTGAAGCAACTTCCT----CGTTTGCTC------------------------TGTGATCTGT------GCTGTCG----TAGATGAG---ATTT---------ACT-------------GATTTGGC-----------------------GTGCGCCG--GTTGTATTCTGTCATGGGGTTCAGTGGGCTGTGTAATACCTTGCTCTG---TACTT-CTGTTCAATGCAATCACTTCTATTCTGAA'
identical=0
for x in range(0,len(humanh4)):
	if humanh4[x]==wheath4[x]:
		identical+=1

seqidentity=identical/len(humanh4)
print(f'Identical nt: {identical}')
print(f'Alignment nt: {len(humanh4)}')
print(f'Sequence ID {seqidentity*100:.2f}%')
